/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SeasonYearRouteImport } from './routes/$season.$year'
import { Route as SeasonYearIdRouteImport } from './routes/$season.$year.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonYearRoute = SeasonYearRouteImport.update({
  id: '/$season/$year',
  path: '/$season/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonYearIdRoute = SeasonYearIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SeasonYearRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$season/$year': typeof SeasonYearRouteWithChildren
  '/$season/$year/$id': typeof SeasonYearIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$season/$year': typeof SeasonYearRouteWithChildren
  '/$season/$year/$id': typeof SeasonYearIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$season/$year': typeof SeasonYearRouteWithChildren
  '/$season/$year/$id': typeof SeasonYearIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$season/$year' | '/$season/$year/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$season/$year' | '/$season/$year/$id'
  id: '__root__' | '/' | '/$season/$year' | '/$season/$year/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeasonYearRoute: typeof SeasonYearRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$season/$year': {
      id: '/$season/$year'
      path: '/$season/$year'
      fullPath: '/$season/$year'
      preLoaderRoute: typeof SeasonYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$season/$year/$id': {
      id: '/$season/$year/$id'
      path: '/$id'
      fullPath: '/$season/$year/$id'
      preLoaderRoute: typeof SeasonYearIdRouteImport
      parentRoute: typeof SeasonYearRoute
    }
  }
}

interface SeasonYearRouteChildren {
  SeasonYearIdRoute: typeof SeasonYearIdRoute
}

const SeasonYearRouteChildren: SeasonYearRouteChildren = {
  SeasonYearIdRoute: SeasonYearIdRoute,
}

const SeasonYearRouteWithChildren = SeasonYearRoute._addFileChildren(
  SeasonYearRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeasonYearRoute: SeasonYearRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
